###
GET http://localhost:5243/api/user
Authorization: Bearer my-secret-token
###
GET http://localhost:5243/api/user/0
Authorization: Bearer my-secret-token

###
POST http://localhost:5243/api/user
Authorization: Bearer my-secret-token
Content-Type: application/json

{
	"firstName":"Matto",
	"lastName":"Foo",
	"email":"test@gmail.com",
	"department":"HR"
}
###
PUT http://localhost:5243/api/user/1
Authorization: Bearer my-secret-token
Content-Type: application/json

{
	"firstName":"Max",
	"lastName":"Tan",
	"email":"test2@gmail.com",
	"department":"IT"
}
###
DELETE http://localhost:5243/api/user/2
Authorization: Bearer my-secret-token
